# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-06 19:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('priority', models.IntegerField(default=0)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('stuck', 'stuck'), ('in progress', 'in progress'), ('done', 'done'), ('cancel', 'cancel')], max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
